var barData = google.visualization.arrayToDataTable([
    ['0', 'Doanh Thu Bán Vé'],
    ['1', {{one}}],
    ['2',  {{two}}],
    ['3',  {{three}}],
    ['4',  {{for}}],
    ['5',  {{five}}],
    ['6',  {{six}}],
    ['7',  {{seven}}],
    ['8',  {{eight}}],
    ['9',   {{nine}}],
    ['10',  {{ten}}],
    ['21', {{one2}}],
    ['22',  {{two2}}],
    ['23',  {{three2}}],
    ['24',  {{for2}}],
    ['25',  {{five2}}],
    ['26',  {{six2}}],
    ['27',  {{seven2}}],
    ['28',  {{eight2}}],
    ['29',   {{nine2}}],
    ['30',  {{ten2}}],
    ['31',  {{one3}}],
]);